### ISSUE TITLE
Do your tried show multiple characters in one image by using multiple embedings?

### ISSUE THREAD

**Issue by ghosthamlet** [BelieveDiffusion/tutorials#4]
Thanks for your wonderful tutorial: https://github.com/BelieveDiffusion/tutorials/blob/main/consistent_character_embedding/README.md, i have leaned so much useful details from this tutorial.

Do your tried show multiple characters in one image by using multiple embedings? 
or are there any other methods have you successed to do that?

**Comment by BelieveDiffusion** [comment]
Hello! I haven't tried it myself, but I believe you can use something like [Latent Couple](https://github.com/miZyind/sd-webui-latent-couple) to combine two separate embeddings or character descriptions in a single image.

**Comment by ghosthamlet** [comment]
Thanks for the recommendation. Can't wait to read your next tutorial.
